#PostgreSql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d5m83t1r0fns73epr1b0-a.singapore-postgres.render.com/fintrack_x0v9
spring.datasource.username=fintrack_x0v9_user
spring.datasource.password=574ucDZCk2CBdccif9HEwxxe5vKARleX