spring.application.name=fintrack

#MySql Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/fintrackappdb
spring.datasource.username=root
spring.datasource.password=root

server.servlet.context-path=/api/v1.0

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Email Configuration - Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_EMAIL}
spring.mail.password=${BREVO_SMTP_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.protocol=smtp
spring.mail.from=${BREVO_FROM_EMAIL}

//JWT
jwt.secret=myVerySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong
jwt.expiration=86400000

finance.tracker.frontend.url=http://localhost:5173